name: atmoseer
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - conda-libmamba-solver
  - conda-forge::cdsapi==0.6.1
  - conda-forge::cfgrib==0.9.10.4
  - conda-forge::fastparquet==2024.2.0
  - conda-forge::folium==0.16.0
  - conda-forge::metpy==1.6.1
  - conda-forge::missingno==0.5.2
  - conda-forge::notebook==7.1.2
  - conda-forge::numpy==1.26.4
  - conda-forge::pandas==2.2.1
  - conda-forge::pandera==0.18.3
  - conda-forge::pyarrow==15.0.2
  - conda-forge::pyyaml==6.0.1
  - conda-forge::scikit-learn==1.4.1.post1
  - conda-forge::statsmodels==0.14.1
  - conda-forge::xarray==2024.3.0
  - pytorch::pytorch==2.2.2
